### ISSUE TITLE
Im not able to run on my server-Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by AbuHelweh** [kby-ai/FaceCapture-Web#1]
facecapture-web/liveface.data:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
liveface.js:1  Uncaught Error: Not Found : http://localhost/facecapture-web/liveface.data
    at xhr.onload (liveface.js:1:2534)

**Comment by ml13571** [comment]
It's because license was expired !
It's working well on my end right now
